name: model-env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - numpy~=1.21.0
  - pip=21.3.1
  - scikit-learn~=1.0.0
  - scipy~=1.7.0
  - pandas~=1.3.0
  - pip:
      - azureml-core==1.51.0
      - azureml-defaults==1.51.0
      - azureml-mlflow==1.51.0
      - azureml-telemetry==1.51.0
      - psutil~=5.8.0
      - tqdm~=4.62.0
      - ipykernel~=6.0
      - matplotlib~=3.5.0
      - debugpy~=1.6.3
